version: '3'

services:
  private:
    image: ghcr.io/ovesorg/migration-service:dev
    # build: .
    # container_name: auth-microservice
    volumes:
      - '/app'
      - '/app/node_modules'
      # - '.:/app'
    ports:
      - 3010:3333
    environment:
      - CHOKIDAR_USEPOLLING=true
